config/routes.rb
Rails::application.routes.draw do
  
 devise_for :users
  #resources :advertisements
  
     resources :topics do
      resources :posts, except: [:index]
    end

 get 'about' => 'welcome#about'

  root to: 'welcome#index'

end

app/models/advertisement.rb
class Advertisement < ActiveRecord::Base
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments
  belongs_to :user
    belongs_to :topic
  
  #default_scope { order('created_at DESC') }
  scope :ordered_by_title, -> { order(title: 'DESC') }
  scope :ordered_by_reverse_created_at, -> { order(created_at: 'ASC') }

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  has_many :posts
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :posts

def admin?
  role == 'admin'
end

def moderator?
  role == 'moderator'
end

end

app/controllers/advertisement_controller.rb
class AdvertisementController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/advertisements_controller.rb
class AdvertisementsController < ApplicationController
  def index
    @advertisements = Advertisement.all
  end

  def show
    @advertisement = Advertisement.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit

  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  #before_action :flash_attack

      rescue_from Pundit::NotAuthorizedError do |exception| 
        redirect_to root_url, alert: exception.message
      end 

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end

  #def flash_attack
    #flash.now[:notice] = "Flash Attack!"
  #end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_before_action :flash_attack, only:[:index, :new]

  def index
    @posts = policy_scope(Post)
  end

  def show
    @post = Post.find(params[:id])
    authorize @post
    @topic = Topic.find(params[:topic_id])
  end

  def new
    @topic = Topic.find(params[:topic_id])
    @post = Post.new
    authorize @post
  end

  def create
    @topic = Topic.find(params[:topic_id])
    @post = current_user.posts.build(params.require(:post).permit(:title, :body))
    authorize @post
    if @post.save
      flash[:notice] = "Post was saved."
      redirect_to [@topic, @post]
    else
      flash[:error] = "There was an error saving the post. Please try again."
      render :new
    end
  end

  def edit
    @topic = Topic.find(params[:topic_id])
    @post = Post.find(params[:id])
    authorize @post
  end

  def update
    @topic = Topic.find(params[:topic_id])
    @post = Post.find(params[:id])
    authorize @post
    if @post.update_attributes(params.require(:post).permit(:title, :body))
      flash[:notice] = "Post was updated."
      redirect_to [@topic, @post]
    else
      flash[:error] = "There was an error saving the post. Please try again."
      render :edit
    end
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  
  def index
    @topics = Topic.all
    authorize @topics
  end

  def new
    @topic = Topic.new
    authorize @topic
  end

  def show
    @topic = Topic.find(params[:id])
    @posts = @topic.posts
    authorize @topic
  end

  def edit
    @topic = Topic.find(params[:id])
    authorize @topic
  end

  def create
    @topic = Topic.new(params.require(:topic).permit(:name, :description, :public))
    authorize @topic
    if @topic.save
      redirect_to @topic, notice: "Topic was saved successfully."
    else
      flash[:error] = "Error creating topic. Please try again."
      render :new
    end
  end

      def update
        @topic = Topic.find(params[:id])
        authorize @topic
          if @topic.update_attributes(params.require(:topic).permit(:name, :description, :public))
            redirect_to @topic
          else
            flash[:error] = "Error saving topic. Please try again."
            render :edit
          end
      end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end
end

app/helpers/advertisement_helper.rb
module AdvertisementHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def my_name
    "Ulysses E Spellman"
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/advertisement/index.html.erb
<h1>Advertisement#index</h1>
<p>Find me in app/views/advertisement/index.html.erb</p>

app/views/advertisement/show.html.erb
<h1>Advertisement#show</h1>
<p>Find me in app/views/advertisement/show.html.erb</p>

app/views/advertisements/index.html.erb
<h1>Advertisement</h1>
<% @advertisements.each do |advertisement| %>
  <div class="media">
    <div class="media-body">
      <h4 class="media-heading">
        <%= link_to advertisement.title, advertisement %>
      </h4>
    </div>
  </div>
  <% end %>

app/views/advertisements/show.html.erb
<h1><%= @advertisement.title %></h1>
<p><%= @advertisement.copy %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bloccit</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container">
  <ul class="nav nav-tabs">
    <li><%= link_to "Bloccit", root_path %></li>
    <li><%= link_to "About", about_path %></li>

      <div class="pull-right user-info">
        <% if current_user %>
          Hello <%= current_user.name %>! <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
          <% else %>
            <%= link_to "Sign In", new_user_session_path %> or
            <%= link_to "Sign Up", new_user_registration_path %>
        <% end %>
      </div>
  </ul>

      <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
      <% elsif flash[:error] %>
      </div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
         <%= flash[:error] %>
      </div>
      <% elsif flash[:alert] %>
      </div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
         <%= flash[:alert] %>
      </div>
      <% end %>

<%= yield %>
</div>

</body>
</html>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for posts</p>
    <ul>
      <li>Make sure that it rhymes.</li>
      <li>Don't use the letter "A".</li>
      <li>The incessant use of hashtags will get you banned.</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= form_for [@topic, @post] do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control', placeholder: "End post title" %>
    </div>
    <div class="form-group">
      <%= f.label :body %>
      <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter post body" %>
    </div>
    <div class="form-group">
      <%= f.submit "Save", class: 'btn btn-success' %>
    </div>
    <% end %>
  </div>
</div>

app/views/posts/index.html.erb
<h1>All Posts</h1>

  <% if policy(Post.new).create? %>
    <%= link_to "New Post", new_post_path, class: 'btn btn-success' %>
  <% end %>

<% @posts.each do |post| %>
  <div class="media">
    <div class="media-body">
      <h4 class="media-heading">
        <%= link_to post.title, post_path(post) %>
      </h4>
          <small>
            submitted <%= time_ago_in_words(post.created_at) %> ago by <%= post.user %><br/>
            <%= post.comments.count %> Comments
          </small>
    </div>
  </div>
  <% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for posts</p>
    <ul>
      <li>Make sure it rhymes.</li>
      <li>Don't use the letter "A".</li>
      <li>The incessant use of hashtags will get you banned.</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= form_for [@topic, @post] do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: "Enter post title" %>
      </div>
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter post body" %>
      </div>
      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
      </div>
      <% end %>
    </div>
  </div>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

<div class="row">
  <div class="col-md-8">
    <p><%= @post.body %></p>
  </div>
  <div class="col-md-4">
    <% if policy(@post).edit? %>
      <%= link_to "Edit", edit_topic_post_path(@topic, @post), class: 'btn btn-success' %>
    <% end %>
  </div>
</div>
<p><%= @post.body %></p>

app/views/topics/edit.html.erb
<h1>Edit Topic</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for topics:</p>
    <ul>
      <li>Make sure the topic is appropriate.</li>
      <li>Never insult dogs.</li>
      <li>Smile when you type.</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= form_for @topic do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control', placeholder: "Enter topic name" %>
      </div>
      <div class="form-group">
        <%= f.label :description, rows: 8, class: 'form-control', placeholder: "Enter topic description" %>
      </div>
      <div class="form-group">
        <%= f.label :public, class: 'checkbox' do %>
          <%= f.check_box :public %> Public topic
        <% end %>
      </div>
      <%= f.submit "Save", class: 'btn btn-success' %>
      <% end %>
    </div>
  </div>
  

app/views/topics/index.html.erb
<h1>Topics</h1>

<div class="row">
  <div class="col-md-8">
    <% @topics.each do |topic| %>
      <div class="media">
        <div class="media-body">
          <h4 class="media-heading">
            <%= link_to topic.name, topic %>
          </h4>
          <small>
            <%= topic.description %>
          </small>
        </div>
      </div>
      <% end %>
    </div>
    <div class="col-md-4">
      <% if policy(Topic.new).create? %>
        <%= link_to "New Topic", new_topic_path, class: 'btn btn-success' %>
      <% end %>
    </div>
  </div>
  

app/views/topics/new.html.erb
<h1>New Topic</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for topics:</p>
    <ul>
      <li>Make sure the topic is appropriate.</li>
      <li>Never insult dogs.</li>
      <li>Smile when you type.</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= form_for @topic do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class:'form-control', placeholder: "Enter topic name" %>
      </div>
      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, rows: 8, class: 'form-control', placeholder: "Enter topic description" %>
      </div>
      <div class="form-group">
        <%= f.label :public, class: 'checkbox' do %>
          <%= f.check_box :public %> Public topic
        <% end %>
      </div>
      <%= f.submit "Save", class: 'btn btn-success' %>
    <% end %>
  </div>
</div>

app/views/topics/show.html.erb
<h1><%= @topic.name %></h1>

<% if policy(@topic).update? %>
  <%= link_to "Edit Topic", edit_topic_path, class: 'btn btn-success' %>
<% end %>

<div class="row">
  <div class="col-md-8">
    <p class="lead"><%= @topic.description %></p>
    <% @posts.each do |post| %>
      <div class="media">
        <div class="media-body">
          <h4 class="media-heading">
            <%= link_to post.title, [@topic, post] %>
          </h4>
          <small>
            submitted <%= time_ago_in_words(post.created_at) %> ago by <%= post.user.name %><br/>
            <%= post.comments.count %> Comments
          </small> 
        </div>
      </div>
      <% end %>
    </div>
    <div class="col-md-4">
      <% if policy(Post.new).create? %>
        <%= link_to "New Post", new_topic_post_path(@topic), class: 'btn btn-success' %>
      <% end %>
    </div>
  </div>

app/views/welcome/about.html.erb
<h1>About Bloccit</h1>
<p>Created by: <%= my_name %></p>

<%= link_to "Follow me", "http://www.github.com/uspellman", class: "social-btn" %>

app/views/welcome/contact.html.erb
<h1>Welcome#contact</h1>
<p>Find me in app/views/welcome/contact.html.erb</p>

app/views/welcome/index.html.erb
<br />
<div class="jumbotron">
  <h1>Bloccit</h1>
  <p> Bloccit is a resource for sharing links with your friends!</p>
  <p>
      <%= link_to "Sign In", new_user_session_path, class: 'btn btn-primary' %> or
      <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary' %> today!
  </p>
</div>

<div class="row">
  <div class="col-md-4">
    <h2>Solves world hunger</h2>
    <p>Bloccit will deliver food and water to those in need, all over the world.</p>
  </div>
  <div class="col-md-4">
    <h2>Eliminates poverty</h2>
    <p>Bloccit will deliver money and education to those in need, all over the world.</p>
  </div>
  <div class="col-md-4">
    <h2>Makes you better looking</h2>
    <p>Bloccit will make you better looking: it's scientifically proven to make men look like Ryan Gosling and women look like Shakira.</p>